services:
  - type: web
    name: konar-law-firm-website
    env: node
    buildCommand: "npm run build"
    startCommand: "serve -s build"
    staticPublishPath: "/build"
    routes:
      - src: "/**"
        dest: "/index.html"
